#!/bin/bash
set -euo pipefail

DATASET="${1:-mmlu}"
NUM_SHARDS="${NUM_SHARDS:-16}"
GENERAL_SHARDS="${GENERAL_SHARDS:-4}"
PREEMPT_SHARDS="${PREEMPT_SHARDS:-12}"
GENERAL_PARALLEL="${GENERAL_PARALLEL:-4}"
PREEMPT_PARALLEL="${PREEMPT_PARALLEL:-12}"
N_SAMPLES="${N_SAMPLES:-100}"
TRACE_SAMPLES="${TRACE_SAMPLES:-2}"
GPU_SPEC="${GPU_SPEC:-gpu:L40S:2}"
CPUS_PER_TASK="${CPUS_PER_TASK:-8}"
MEMORY="${MEMORY:-96G}"
TIME_LIMIT="${TIME_LIMIT:-02:00:00}"
OUTPUT_SLUG="${OUTPUT_SLUG:-qwen_1p5b_7b_14b_hybrid16_l40s}"
RUN_ROOT="/home/$USER/repo/mlsys/CS-Drafting"
SHARD_DIR="$RUN_ROOT/results/shards/${DATASET}_${OUTPUT_SLUG}"
MS_NAME="${MS_NAME:-Qwen/Qwen2.5-1.5B-Instruct}"
MM_NAME="${MM_NAME:-Qwen/Qwen2.5-7B-Instruct}"
ML_NAME="${ML_NAME:-Qwen/Qwen2.5-14B-Instruct}"
SMALL_WINDOW="${SMALL_WINDOW:-3}"
MIDDLE_WINDOW="${MIDDLE_WINDOW:-9}"
HIERARCHICAL_VARIANT="${HIERARCHICAL_VARIANT:-window_fill}"
PROXY_THRESHOLD="${PROXY_THRESHOLD:-}"
MAVG_WINDOW="${MAVG_WINDOW:-5}"
MAX_LENGTH="${MAX_LENGTH:-200}"

if [ "$((GENERAL_SHARDS + PREEMPT_SHARDS))" -ne "$NUM_SHARDS" ]; then
  echo "GENERAL_SHARDS + PREEMPT_SHARDS must equal NUM_SHARDS" >&2
  exit 1
fi

mkdir -p "$SHARD_DIR"
mkdir -p "/home/$USER/logs/sbatch"

cd "$RUN_ROOT"

GENERAL_JOB_ID="$(
  sbatch --parsable \
    -p general \
    --gres="$GPU_SPEC" \
    --cpus-per-task="$CPUS_PER_TASK" \
    --mem="$MEMORY" \
    --time="$TIME_LIMIT" \
    --array="0-$((GENERAL_SHARDS - 1))%${GENERAL_PARALLEL}" \
    --export=ALL,N_SAMPLES="$N_SAMPLES",NUM_SHARDS="$NUM_SHARDS",TRACE_SAMPLES="$TRACE_SAMPLES",OUTPUT_SLUG="$OUTPUT_SLUG",RESULT_DIR="$SHARD_DIR",SHARD_OFFSET=0,MS_NAME="$MS_NAME",MM_NAME="$MM_NAME",ML_NAME="$ML_NAME",SMALL_WINDOW="$SMALL_WINDOW",MIDDLE_WINDOW="$MIDDLE_WINDOW",HIERARCHICAL_VARIANT="$HIERARCHICAL_VARIANT",PROXY_THRESHOLD="$PROXY_THRESHOLD",MAVG_WINDOW="$MAVG_WINDOW",MAX_LENGTH="$MAX_LENGTH" \
    scripts/run_fixed_window_babel.sbatch "$DATASET"
)"

PREEMPT_JOB_ID="$(
  sbatch --parsable \
    -p preempt \
    --gres="$GPU_SPEC" \
    --cpus-per-task="$CPUS_PER_TASK" \
    --mem="$MEMORY" \
    --time="$TIME_LIMIT" \
    --array="0-$((PREEMPT_SHARDS - 1))%${PREEMPT_PARALLEL}" \
    --export=ALL,N_SAMPLES="$N_SAMPLES",NUM_SHARDS="$NUM_SHARDS",TRACE_SAMPLES="$TRACE_SAMPLES",OUTPUT_SLUG="$OUTPUT_SLUG",RESULT_DIR="$SHARD_DIR",SHARD_OFFSET="$GENERAL_SHARDS",MS_NAME="$MS_NAME",MM_NAME="$MM_NAME",ML_NAME="$ML_NAME",SMALL_WINDOW="$SMALL_WINDOW",MIDDLE_WINDOW="$MIDDLE_WINDOW",HIERARCHICAL_VARIANT="$HIERARCHICAL_VARIANT",PROXY_THRESHOLD="$PROXY_THRESHOLD",MAVG_WINDOW="$MAVG_WINDOW",MAX_LENGTH="$MAX_LENGTH" \
    scripts/run_fixed_window_babel.sbatch "$DATASET"
)"

REPAIR_JOB_ID="$(
  sbatch --parsable \
    --dependency="afterany:${GENERAL_JOB_ID}:${PREEMPT_JOB_ID}" \
    --export=ALL,N_SAMPLES="$N_SAMPLES",TRACE_SAMPLES="$TRACE_SAMPLES",RESULT_DIR="$SHARD_DIR",RERUN_PARTITION=general,RERUN_GPU_SPEC="$GPU_SPEC",RERUN_CPUS_PER_TASK="$CPUS_PER_TASK",RERUN_MEMORY="$MEMORY",RERUN_TIME_LIMIT="$TIME_LIMIT",MS_NAME="$MS_NAME",MM_NAME="$MM_NAME",ML_NAME="$ML_NAME",SMALL_WINDOW="$SMALL_WINDOW",MIDDLE_WINDOW="$MIDDLE_WINDOW",HIERARCHICAL_VARIANT="$HIERARCHICAL_VARIANT",PROXY_THRESHOLD="$PROXY_THRESHOLD",MAVG_WINDOW="$MAVG_WINDOW",MAX_LENGTH="$MAX_LENGTH" \
    scripts/repair_fixed_window_shards.sbatch "$DATASET" "$OUTPUT_SLUG" "$NUM_SHARDS"
)"

echo "Submitted general shard array job: $GENERAL_JOB_ID"
echo "Submitted preempt shard array job: $PREEMPT_JOB_ID"
echo "Submitted repair job: $REPAIR_JOB_ID"
echo "Shard outputs: $SHARD_DIR"
echo "Merged output: $RUN_ROOT/results/fixed_window_compare_${DATASET}_${OUTPUT_SLUG}.json"
