#!/bin/bash
set -euo pipefail

DATASET="${1:-mmlu}"
NUM_SHARDS="${NUM_SHARDS:-16}"
GENERAL_SHARDS="${GENERAL_SHARDS:-4}"
PREEMPT_SHARDS="${PREEMPT_SHARDS:-12}"
GENERAL_PARALLEL="${GENERAL_PARALLEL:-4}"
PREEMPT_PARALLEL="${PREEMPT_PARALLEL:-12}"
TRACE_SAMPLES="${TRACE_SAMPLES:-4}"
GPU_SPEC="${GPU_SPEC:-gpu:L40S:2}"
CPUS_PER_TASK="${CPUS_PER_TASK:-8}"
MEMORY="${MEMORY:-96G}"
TIME_LIMIT="${TIME_LIMIT:-08:00:00}"
OUTPUT_SLUG="${OUTPUT_SLUG:-qwen_1p5b_7b_14b_acsd_full_trace_v1}"
RUN_ROOT="/home/$USER/repo/mlsys/CS-Drafting"
SHARD_DIR="$RUN_ROOT/results/shards/${DATASET}_${OUTPUT_SLUG}"
BRANCH_ROOT="${BRANCH_ROOT:-$RUN_ROOT}"
MS_NAME="${MS_NAME:-Qwen/Qwen2.5-1.5B-Instruct}"
MM_NAME="${MM_NAME:-Qwen/Qwen2.5-7B-Instruct}"
ML_NAME="${ML_NAME:-Qwen/Qwen2.5-14B-Instruct}"
MODE="${MODE:-compare_all}"
K_S="${K_S:-5}"
K_M="${K_M:-4}"
LENIENCY="${LENIENCY:-1}"
TAU="${TAU:-0.4}"
WINDOW_SIZE="${WINDOW_SIZE:-20}"
MAX_LENGTH="${MAX_LENGTH:-200}"
MIDDLE_REFILL="${MIDDLE_REFILL:-1}"
SHADOW_MIDDLE="${SHADOW_MIDDLE:-0}"
DRAFT_WINDOW_POLICY="${DRAFT_WINDOW_POLICY:-fixed}"
DYNAMIC_K_S_MIN="${DYNAMIC_K_S_MIN:-2}"
DYNAMIC_K_S_MAX="${DYNAMIC_K_S_MAX:-8}"
DYNAMIC_K_M_MIN="${DYNAMIC_K_M_MIN:-2}"
DYNAMIC_K_M_MAX="${DYNAMIC_K_M_MAX:-8}"
DYNAMIC_ACCEPTANCE_LOW="${DYNAMIC_ACCEPTANCE_LOW:-0.5}"
DYNAMIC_ACCEPTANCE_HIGH="${DYNAMIC_ACCEPTANCE_HIGH:-0.8}"
DYNAMIC_WINDOW_STEP="${DYNAMIC_WINDOW_STEP:-1}"

if [ "$((GENERAL_SHARDS + PREEMPT_SHARDS))" -ne "$NUM_SHARDS" ]; then
  echo "GENERAL_SHARDS + PREEMPT_SHARDS must equal NUM_SHARDS" >&2
  exit 1
fi

case "$DATASET" in
  mmlu)
    N_SAMPLES="${N_SAMPLES:-14042}"
    ;;
  gsm8k)
    N_SAMPLES="${N_SAMPLES:-1319}"
    ;;
  *)
    echo "Unsupported dataset: $DATASET" >&2
    exit 1
    ;;
esac

mkdir -p "$SHARD_DIR"
mkdir -p "/home/$USER/logs/sbatch"

cd "$RUN_ROOT"

GENERAL_JOB_ID="$(
  sbatch --parsable \
    -p general \
    --gres="$GPU_SPEC" \
    --cpus-per-task="$CPUS_PER_TASK" \
    --mem="$MEMORY" \
    --time="$TIME_LIMIT" \
    --array="0-$((GENERAL_SHARDS - 1))%${GENERAL_PARALLEL}" \
    --export=ALL,N_SAMPLES="$N_SAMPLES",NUM_SHARDS="$NUM_SHARDS",TRACE_SAMPLES="$TRACE_SAMPLES",OUTPUT_SLUG="$OUTPUT_SLUG",RESULT_DIR="$SHARD_DIR",SHARD_OFFSET=0,BRANCH_ROOT="$BRANCH_ROOT",MODE="$MODE",MS_NAME="$MS_NAME",MM_NAME="$MM_NAME",ML_NAME="$ML_NAME",K_S="$K_S",K_M="$K_M",LENIENCY="$LENIENCY",TAU="$TAU",WINDOW_SIZE="$WINDOW_SIZE",MAX_LENGTH="$MAX_LENGTH",MIDDLE_REFILL="$MIDDLE_REFILL",SHADOW_MIDDLE="$SHADOW_MIDDLE",DRAFT_WINDOW_POLICY="$DRAFT_WINDOW_POLICY",DYNAMIC_K_S_MIN="$DYNAMIC_K_S_MIN",DYNAMIC_K_S_MAX="$DYNAMIC_K_S_MAX",DYNAMIC_K_M_MIN="$DYNAMIC_K_M_MIN",DYNAMIC_K_M_MAX="$DYNAMIC_K_M_MAX",DYNAMIC_ACCEPTANCE_LOW="$DYNAMIC_ACCEPTANCE_LOW",DYNAMIC_ACCEPTANCE_HIGH="$DYNAMIC_ACCEPTANCE_HIGH",DYNAMIC_WINDOW_STEP="$DYNAMIC_WINDOW_STEP" \
    scripts/run_acsd_compare_babel.sbatch "$DATASET"
)"

PREEMPT_JOB_ID="$(
  sbatch --parsable \
    -p preempt \
    --gres="$GPU_SPEC" \
    --cpus-per-task="$CPUS_PER_TASK" \
    --mem="$MEMORY" \
    --time="$TIME_LIMIT" \
    --array="0-$((PREEMPT_SHARDS - 1))%${PREEMPT_PARALLEL}" \
    --export=ALL,N_SAMPLES="$N_SAMPLES",NUM_SHARDS="$NUM_SHARDS",TRACE_SAMPLES="$TRACE_SAMPLES",OUTPUT_SLUG="$OUTPUT_SLUG",RESULT_DIR="$SHARD_DIR",SHARD_OFFSET="$GENERAL_SHARDS",BRANCH_ROOT="$BRANCH_ROOT",MODE="$MODE",MS_NAME="$MS_NAME",MM_NAME="$MM_NAME",ML_NAME="$ML_NAME",K_S="$K_S",K_M="$K_M",LENIENCY="$LENIENCY",TAU="$TAU",WINDOW_SIZE="$WINDOW_SIZE",MAX_LENGTH="$MAX_LENGTH",MIDDLE_REFILL="$MIDDLE_REFILL",SHADOW_MIDDLE="$SHADOW_MIDDLE",DRAFT_WINDOW_POLICY="$DRAFT_WINDOW_POLICY",DYNAMIC_K_S_MIN="$DYNAMIC_K_S_MIN",DYNAMIC_K_S_MAX="$DYNAMIC_K_S_MAX",DYNAMIC_K_M_MIN="$DYNAMIC_K_M_MIN",DYNAMIC_K_M_MAX="$DYNAMIC_K_M_MAX",DYNAMIC_ACCEPTANCE_LOW="$DYNAMIC_ACCEPTANCE_LOW",DYNAMIC_ACCEPTANCE_HIGH="$DYNAMIC_ACCEPTANCE_HIGH",DYNAMIC_WINDOW_STEP="$DYNAMIC_WINDOW_STEP" \
    scripts/run_acsd_compare_babel.sbatch "$DATASET"
)"

REPAIR_JOB_ID="$(
  sbatch --parsable \
    --dependency="afterany:${GENERAL_JOB_ID}:${PREEMPT_JOB_ID}" \
    --export=ALL,N_SAMPLES="$N_SAMPLES",TRACE_SAMPLES="$TRACE_SAMPLES",RESULT_DIR="$SHARD_DIR",RERUN_PARTITION=general,RERUN_GPU_SPEC="$GPU_SPEC",RERUN_CPUS_PER_TASK="$CPUS_PER_TASK",RERUN_MEMORY="$MEMORY",RERUN_TIME_LIMIT="$TIME_LIMIT",BRANCH_ROOT="$BRANCH_ROOT",MODE="$MODE",MS_NAME="$MS_NAME",MM_NAME="$MM_NAME",ML_NAME="$ML_NAME",K_S="$K_S",K_M="$K_M",LENIENCY="$LENIENCY",TAU="$TAU",WINDOW_SIZE="$WINDOW_SIZE",MAX_LENGTH="$MAX_LENGTH",MIDDLE_REFILL="$MIDDLE_REFILL",SHADOW_MIDDLE="$SHADOW_MIDDLE",DRAFT_WINDOW_POLICY="$DRAFT_WINDOW_POLICY",DYNAMIC_K_S_MIN="$DYNAMIC_K_S_MIN",DYNAMIC_K_S_MAX="$DYNAMIC_K_S_MAX",DYNAMIC_K_M_MIN="$DYNAMIC_K_M_MIN",DYNAMIC_K_M_MAX="$DYNAMIC_K_M_MAX",DYNAMIC_ACCEPTANCE_LOW="$DYNAMIC_ACCEPTANCE_LOW",DYNAMIC_ACCEPTANCE_HIGH="$DYNAMIC_ACCEPTANCE_HIGH",DYNAMIC_WINDOW_STEP="$DYNAMIC_WINDOW_STEP" \
    scripts/repair_acsd_shards.sbatch "$DATASET" "$OUTPUT_SLUG" "$NUM_SHARDS"
)"

echo "Submitted general shard array job: $GENERAL_JOB_ID"
echo "Submitted preempt shard array job: $PREEMPT_JOB_ID"
echo "Submitted repair job: $REPAIR_JOB_ID"
echo "Shard outputs: $SHARD_DIR"
echo "Merged output: $RUN_ROOT/results/acsd_compare_${DATASET}_${OUTPUT_SLUG}.json"
