#!/bin/bash
set -euo pipefail

DATASET="${1:-mmlu}"
NUM_SHARDS="${NUM_SHARDS:-4}"
MAX_PARALLEL_SHARDS="${MAX_PARALLEL_SHARDS:-4}"
N_SAMPLES="${N_SAMPLES:-100}"
TRACE_SAMPLES="${TRACE_SAMPLES:-2}"
PARTITION="${PARTITION:-general}"
GPU_SPEC="${GPU_SPEC:-gpu:L40:2}"
CPUS_PER_TASK="${CPUS_PER_TASK:-4}"
MEMORY="${MEMORY:-64G}"
TIME_LIMIT="${TIME_LIMIT:-00:25:00}"
OUTPUT_SLUG="${OUTPUT_SLUG:-qwen_1p5b_7b_14b_sharded}"
RUN_ROOT="/home/$USER/repo/mlsys/CS-Drafting"
SHARD_DIR="$RUN_ROOT/results/shards/${DATASET}_${OUTPUT_SLUG}"
MS_NAME="${MS_NAME:-Qwen/Qwen2.5-1.5B-Instruct}"
MM_NAME="${MM_NAME:-Qwen/Qwen2.5-7B-Instruct}"
ML_NAME="${ML_NAME:-Qwen/Qwen2.5-14B-Instruct}"
SMALL_WINDOW="${SMALL_WINDOW:-3}"
MIDDLE_WINDOW="${MIDDLE_WINDOW:-9}"
HIERARCHICAL_VARIANT="${HIERARCHICAL_VARIANT:-window_fill}"
PROXY_THRESHOLD="${PROXY_THRESHOLD:-}"
MAVG_WINDOW="${MAVG_WINDOW:-5}"
MAX_LENGTH="${MAX_LENGTH:-200}"

mkdir -p "$SHARD_DIR"
mkdir -p "/home/$USER/logs/sbatch"

ARRAY_SPEC="0-$((NUM_SHARDS - 1))%${MAX_PARALLEL_SHARDS}"

cd "$RUN_ROOT"

SHARD_JOB_ID="$(
  sbatch --parsable \
    -p "$PARTITION" \
    --gres="$GPU_SPEC" \
    --cpus-per-task="$CPUS_PER_TASK" \
    --mem="$MEMORY" \
    --time="$TIME_LIMIT" \
    --array="$ARRAY_SPEC" \
    --export=ALL,N_SAMPLES="$N_SAMPLES",NUM_SHARDS="$NUM_SHARDS",TRACE_SAMPLES="$TRACE_SAMPLES",OUTPUT_SLUG="$OUTPUT_SLUG",MS_NAME="$MS_NAME",MM_NAME="$MM_NAME",ML_NAME="$ML_NAME",SMALL_WINDOW="$SMALL_WINDOW",MIDDLE_WINDOW="$MIDDLE_WINDOW",HIERARCHICAL_VARIANT="$HIERARCHICAL_VARIANT",PROXY_THRESHOLD="$PROXY_THRESHOLD",MAVG_WINDOW="$MAVG_WINDOW",MAX_LENGTH="$MAX_LENGTH" \
    scripts/run_fixed_window_babel.sbatch "$DATASET"
)"

REPAIR_JOB_ID="$(
  sbatch --parsable \
    --dependency="afterany:${SHARD_JOB_ID}" \
    --export=ALL,N_SAMPLES="$N_SAMPLES",TRACE_SAMPLES="$TRACE_SAMPLES",RESULT_DIR="$SHARD_DIR",RERUN_PARTITION="$PARTITION",RERUN_GPU_SPEC="$GPU_SPEC",RERUN_CPUS_PER_TASK="$CPUS_PER_TASK",RERUN_MEMORY="$MEMORY",RERUN_TIME_LIMIT="$TIME_LIMIT",MS_NAME="$MS_NAME",MM_NAME="$MM_NAME",ML_NAME="$ML_NAME",SMALL_WINDOW="$SMALL_WINDOW",MIDDLE_WINDOW="$MIDDLE_WINDOW",HIERARCHICAL_VARIANT="$HIERARCHICAL_VARIANT",PROXY_THRESHOLD="$PROXY_THRESHOLD",MAVG_WINDOW="$MAVG_WINDOW",MAX_LENGTH="$MAX_LENGTH" \
    scripts/repair_fixed_window_shards.sbatch "$DATASET" "$OUTPUT_SLUG" "$NUM_SHARDS"
)"

echo "Submitted shard array job: $SHARD_JOB_ID"
echo "Submitted repair job: $REPAIR_JOB_ID"
echo "Shard outputs: $SHARD_DIR"
echo "Merged output: $RUN_ROOT/results/fixed_window_compare_${DATASET}_${OUTPUT_SLUG}.json"
