#!/bin/bash
set -euo pipefail

DATASET="${1:?dataset required}"
NUM_SHARDS="${NUM_SHARDS:-48}"
GENERAL_SHARDS="${GENERAL_SHARDS:-12}"
PREEMPT_SHARDS="${PREEMPT_SHARDS:-36}"
GENERAL_PARALLEL="${GENERAL_PARALLEL:-12}"
PREEMPT_PARALLEL="${PREEMPT_PARALLEL:-36}"
N_SAMPLES="${N_SAMPLES:-0}"
TRACE_SAMPLES="${TRACE_SAMPLES:-0}"
GPU_SPEC="${GPU_SPEC:-gpu:A6000:1}"
CPUS_PER_TASK="${CPUS_PER_TASK:-12}"
MEMORY="${MEMORY:-96G}"
TIME_LIMIT="${TIME_LIMIT:-06:00:00}"
OUTPUT_SLUG="${OUTPUT_SLUG:-qwen_0p5b_1p5b_14b_focus_selective_full_a6000}"
RUN_ROOT="/home/$USER/repo/mlsys/CS-Drafting"
SHARD_DIR="$RUN_ROOT/results/shards/${DATASET}_${OUTPUT_SLUG}"
MS_NAME="${MS_NAME:-Qwen/Qwen2.5-0.5B-Instruct}"
MM_NAME="${MM_NAME:-Qwen/Qwen2.5-1.5B-Instruct}"
ML_NAME="${ML_NAME:-Qwen/Qwen2.5-14B-Instruct}"
CONFIG_SPECS="${CONFIG_SPECS:-baseline_sw3|baseline|3|-|-|-|;fixed_cascade_sw3_mw6|hierarchical|3|6|double_layer|fixed|baseline_sw3;adaptive_refill_sw3_mw4|hierarchical|3|4|double_layer_refill_on_full_accept|utility|baseline_sw3;adaptive_refill_sw3_mw6|hierarchical|3|6|double_layer_refill_on_full_accept|utility|baseline_sw3;selective_refill_sw3_mw6|hierarchical|3|6|selective_route_refill_on_full_accept|utility|baseline_sw3;baseline_sw5|baseline|5|-|-|-|}"
DYNAMIC_SMALL_WINDOW_MIN="${DYNAMIC_SMALL_WINDOW_MIN:-}"
DYNAMIC_SMALL_WINDOW_MAX="${DYNAMIC_SMALL_WINDOW_MAX:-}"
DYNAMIC_MIDDLE_WINDOW_MIN="${DYNAMIC_MIDDLE_WINDOW_MIN:-3}"
DYNAMIC_MIDDLE_WINDOW_MAX="${DYNAMIC_MIDDLE_WINDOW_MAX:-18}"
DYNAMIC_ACCEPTANCE_LOW="${DYNAMIC_ACCEPTANCE_LOW:-0.6}"
DYNAMIC_ACCEPTANCE_HIGH="${DYNAMIC_ACCEPTANCE_HIGH:-0.8}"
DYNAMIC_WINDOW_STEP="${DYNAMIC_WINDOW_STEP:-1}"
DYNAMIC_UTILITY_MARGIN="${DYNAMIC_UTILITY_MARGIN:-0.0}"
SELECTIVE_ROUTE_WARMUP_BLOCKS="${SELECTIVE_ROUTE_WARMUP_BLOCKS:-1}"
SELECTIVE_ROUTE_HISTORY_WINDOW="${SELECTIVE_ROUTE_HISTORY_WINDOW:-4}"
SELECTIVE_ROUTE_UTILITY_MARGIN="${SELECTIVE_ROUTE_UTILITY_MARGIN:-0.0}"
SELECTIVE_ROUTE_DIRECT_ACCEPTANCE_LOW="${SELECTIVE_ROUTE_DIRECT_ACCEPTANCE_LOW:-0.75}"
SELECTIVE_ROUTE_DIRECT_ACCEPTANCE_HIGH="${SELECTIVE_ROUTE_DIRECT_ACCEPTANCE_HIGH:-0.90}"
SELECTIVE_ROUTE_MIDDLE_ACCEPTANCE_LOW="${SELECTIVE_ROUTE_MIDDLE_ACCEPTANCE_LOW:-0.55}"
SELECTIVE_ROUTE_PROBE_INTERVAL="${SELECTIVE_ROUTE_PROBE_INTERVAL:-0}"
ADAPT_SMALL_WINDOW="${ADAPT_SMALL_WINDOW:-0}"
MAX_LENGTH="${MAX_LENGTH:-200}"

if [ "$((GENERAL_SHARDS + PREEMPT_SHARDS))" -ne "$NUM_SHARDS" ]; then
  echo "GENERAL_SHARDS + PREEMPT_SHARDS must equal NUM_SHARDS" >&2
  exit 1
fi

mkdir -p "$SHARD_DIR"
mkdir -p "/home/$USER/logs/sbatch"

cd "$RUN_ROOT"

GENERAL_JOB_ID="$(
  sbatch --parsable \
    -p general \
    --gres="$GPU_SPEC" \
    --cpus-per-task="$CPUS_PER_TASK" \
    --mem="$MEMORY" \
    --time="$TIME_LIMIT" \
    --array="0-$((GENERAL_SHARDS - 1))%${GENERAL_PARALLEL}" \
    --export=ALL,DATASET="$DATASET",N_SAMPLES="$N_SAMPLES",NUM_SHARDS="$NUM_SHARDS",TRACE_SAMPLES="$TRACE_SAMPLES",OUTPUT_SLUG="$OUTPUT_SLUG",RESULT_DIR="$SHARD_DIR",SHARD_OFFSET=0,MS_NAME="$MS_NAME",MM_NAME="$MM_NAME",ML_NAME="$ML_NAME",CONFIG_SPECS="$CONFIG_SPECS",DYNAMIC_SMALL_WINDOW_MIN="$DYNAMIC_SMALL_WINDOW_MIN",DYNAMIC_SMALL_WINDOW_MAX="$DYNAMIC_SMALL_WINDOW_MAX",DYNAMIC_MIDDLE_WINDOW_MIN="$DYNAMIC_MIDDLE_WINDOW_MIN",DYNAMIC_MIDDLE_WINDOW_MAX="$DYNAMIC_MIDDLE_WINDOW_MAX",DYNAMIC_ACCEPTANCE_LOW="$DYNAMIC_ACCEPTANCE_LOW",DYNAMIC_ACCEPTANCE_HIGH="$DYNAMIC_ACCEPTANCE_HIGH",DYNAMIC_WINDOW_STEP="$DYNAMIC_WINDOW_STEP",DYNAMIC_UTILITY_MARGIN="$DYNAMIC_UTILITY_MARGIN",SELECTIVE_ROUTE_WARMUP_BLOCKS="$SELECTIVE_ROUTE_WARMUP_BLOCKS",SELECTIVE_ROUTE_HISTORY_WINDOW="$SELECTIVE_ROUTE_HISTORY_WINDOW",SELECTIVE_ROUTE_UTILITY_MARGIN="$SELECTIVE_ROUTE_UTILITY_MARGIN",SELECTIVE_ROUTE_DIRECT_ACCEPTANCE_LOW="$SELECTIVE_ROUTE_DIRECT_ACCEPTANCE_LOW",SELECTIVE_ROUTE_DIRECT_ACCEPTANCE_HIGH="$SELECTIVE_ROUTE_DIRECT_ACCEPTANCE_HIGH",SELECTIVE_ROUTE_MIDDLE_ACCEPTANCE_LOW="$SELECTIVE_ROUTE_MIDDLE_ACCEPTANCE_LOW",SELECTIVE_ROUTE_PROBE_INTERVAL="$SELECTIVE_ROUTE_PROBE_INTERVAL",ADAPT_SMALL_WINDOW="$ADAPT_SMALL_WINDOW",MAX_LENGTH="$MAX_LENGTH" \
    scripts/run_fixed_window_focused_babel.sbatch
)"

PREEMPT_JOB_ID="$(
  sbatch --parsable \
    -p preempt \
    --qos=preempt_qos \
    --gres="$GPU_SPEC" \
    --cpus-per-task="$CPUS_PER_TASK" \
    --mem="$MEMORY" \
    --time="$TIME_LIMIT" \
    --array="0-$((PREEMPT_SHARDS - 1))%${PREEMPT_PARALLEL}" \
    --export=ALL,DATASET="$DATASET",N_SAMPLES="$N_SAMPLES",NUM_SHARDS="$NUM_SHARDS",TRACE_SAMPLES="$TRACE_SAMPLES",OUTPUT_SLUG="$OUTPUT_SLUG",RESULT_DIR="$SHARD_DIR",SHARD_OFFSET="$GENERAL_SHARDS",MS_NAME="$MS_NAME",MM_NAME="$MM_NAME",ML_NAME="$ML_NAME",CONFIG_SPECS="$CONFIG_SPECS",DYNAMIC_SMALL_WINDOW_MIN="$DYNAMIC_SMALL_WINDOW_MIN",DYNAMIC_SMALL_WINDOW_MAX="$DYNAMIC_SMALL_WINDOW_MAX",DYNAMIC_MIDDLE_WINDOW_MIN="$DYNAMIC_MIDDLE_WINDOW_MIN",DYNAMIC_MIDDLE_WINDOW_MAX="$DYNAMIC_MIDDLE_WINDOW_MAX",DYNAMIC_ACCEPTANCE_LOW="$DYNAMIC_ACCEPTANCE_LOW",DYNAMIC_ACCEPTANCE_HIGH="$DYNAMIC_ACCEPTANCE_HIGH",DYNAMIC_WINDOW_STEP="$DYNAMIC_WINDOW_STEP",DYNAMIC_UTILITY_MARGIN="$DYNAMIC_UTILITY_MARGIN",SELECTIVE_ROUTE_WARMUP_BLOCKS="$SELECTIVE_ROUTE_WARMUP_BLOCKS",SELECTIVE_ROUTE_HISTORY_WINDOW="$SELECTIVE_ROUTE_HISTORY_WINDOW",SELECTIVE_ROUTE_UTILITY_MARGIN="$SELECTIVE_ROUTE_UTILITY_MARGIN",SELECTIVE_ROUTE_DIRECT_ACCEPTANCE_LOW="$SELECTIVE_ROUTE_DIRECT_ACCEPTANCE_LOW",SELECTIVE_ROUTE_DIRECT_ACCEPTANCE_HIGH="$SELECTIVE_ROUTE_DIRECT_ACCEPTANCE_HIGH",SELECTIVE_ROUTE_MIDDLE_ACCEPTANCE_LOW="$SELECTIVE_ROUTE_MIDDLE_ACCEPTANCE_LOW",SELECTIVE_ROUTE_PROBE_INTERVAL="$SELECTIVE_ROUTE_PROBE_INTERVAL",ADAPT_SMALL_WINDOW="$ADAPT_SMALL_WINDOW",MAX_LENGTH="$MAX_LENGTH" \
    scripts/run_fixed_window_focused_babel.sbatch
)"

REPAIR_JOB_ID="$(
  sbatch --parsable \
    --dependency="afterany:${GENERAL_JOB_ID}:${PREEMPT_JOB_ID}" \
    --export=ALL,DATASET="$DATASET",N_SAMPLES="$N_SAMPLES",TRACE_SAMPLES="$TRACE_SAMPLES",RESULT_DIR="$SHARD_DIR",RERUN_PARTITION=general,RERUN_GPU_SPEC="$GPU_SPEC",RERUN_CPUS_PER_TASK="$CPUS_PER_TASK",RERUN_MEMORY="$MEMORY",RERUN_TIME_LIMIT="$TIME_LIMIT",MS_NAME="$MS_NAME",MM_NAME="$MM_NAME",ML_NAME="$ML_NAME",CONFIG_SPECS="$CONFIG_SPECS",DYNAMIC_SMALL_WINDOW_MIN="$DYNAMIC_SMALL_WINDOW_MIN",DYNAMIC_SMALL_WINDOW_MAX="$DYNAMIC_SMALL_WINDOW_MAX",DYNAMIC_MIDDLE_WINDOW_MIN="$DYNAMIC_MIDDLE_WINDOW_MIN",DYNAMIC_MIDDLE_WINDOW_MAX="$DYNAMIC_MIDDLE_WINDOW_MAX",DYNAMIC_ACCEPTANCE_LOW="$DYNAMIC_ACCEPTANCE_LOW",DYNAMIC_ACCEPTANCE_HIGH="$DYNAMIC_ACCEPTANCE_HIGH",DYNAMIC_WINDOW_STEP="$DYNAMIC_WINDOW_STEP",DYNAMIC_UTILITY_MARGIN="$DYNAMIC_UTILITY_MARGIN",SELECTIVE_ROUTE_WARMUP_BLOCKS="$SELECTIVE_ROUTE_WARMUP_BLOCKS",SELECTIVE_ROUTE_HISTORY_WINDOW="$SELECTIVE_ROUTE_HISTORY_WINDOW",SELECTIVE_ROUTE_UTILITY_MARGIN="$SELECTIVE_ROUTE_UTILITY_MARGIN",SELECTIVE_ROUTE_DIRECT_ACCEPTANCE_LOW="$SELECTIVE_ROUTE_DIRECT_ACCEPTANCE_LOW",SELECTIVE_ROUTE_DIRECT_ACCEPTANCE_HIGH="$SELECTIVE_ROUTE_DIRECT_ACCEPTANCE_HIGH",SELECTIVE_ROUTE_MIDDLE_ACCEPTANCE_LOW="$SELECTIVE_ROUTE_MIDDLE_ACCEPTANCE_LOW",SELECTIVE_ROUTE_PROBE_INTERVAL="$SELECTIVE_ROUTE_PROBE_INTERVAL",ADAPT_SMALL_WINDOW="$ADAPT_SMALL_WINDOW",MAX_LENGTH="$MAX_LENGTH" \
    scripts/repair_fixed_window_focus_shards.sbatch "$DATASET" "$OUTPUT_SLUG" "$NUM_SHARDS"
)"

echo "Submitted general shard array job: $GENERAL_JOB_ID"
echo "Submitted preempt shard array job: $PREEMPT_JOB_ID"
echo "Submitted repair job: $REPAIR_JOB_ID"
echo "Shard outputs: $SHARD_DIR"
echo "Merged output: $RUN_ROOT/results/fixed_window_focus_${DATASET}_${OUTPUT_SLUG}.json"
